name: 🚀 Deploy to GitHub Pages over SSH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Install Node, then build
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: |
          npm ci
          npm run build --config vite.gh-pages.config.js

      # 3) Load your SSH deploy key
      - name: Load deploy key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      # 4) Push the built site to gh-pages
      - name: Deploy to gh-pages
        run: |
          cd dist/public
          rm -rf .git
          git init
          # configure commit identity
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin git@github.com:${{ github.repository }}.git
          git checkout -b gh-pages
          git add .
          git commit -m "🛠 CI deploy"
          git push -f origin gh-pages

